force-app/main/default/objects/Assessment_Definition__c/Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition</label>
    <nameField>
        <label>Assessment Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition_Item__c/Assessment_Definition_Item__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition Item</label>
    <nameField>
        <label>Assessment Definition Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definition Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition_Item__c/fields/Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Definition__c</fullName>
    <label>Assessment Definition</label>
    <referenceTo>Assessment_Definition__c</referenceTo>
    <relationshipLabel>Assessment Definition Items</relationshipLabel>
    <relationshipName>Assessment_Definition_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/AssessmentTriggerHelperUtil.cls
public with sharing class AssessmentTriggerHelperUtil {

    public static void setDefinitionId(List<SObject> records, Schema.SobjectField definitionAssessmentFieldId, Schema.SobjectField itemDefinitionFieldId) {
        AssessmentTriggerHelperUtil.WithoutSharingOps wsops = new AssessmentTriggerHelperUtil.WithoutSharingOps();
        Map<Id, Assessment_Definition_Item__c> items = wsops.getAssessmentDefinitionItems(records, itemDefinitionFieldId);
        for (Sobject r : records) {
            Assessment_Definition_Item__c parentItem = items.get((Id)r.get(itemDefinitionFieldId));
            if (parentItem == null) continue;
            r.put(definitionAssessmentFieldId, (Id)parentItem.get(Schema.Assessment_Definition_Item__c.Assessment_Definition__c));
        }
    }

    private without sharing class WithoutSharingOps {

        public Map<Id, Assessment_Definition_Item__c> getAssessmentDefinitionItems(List<SObject> records, Schema.SobjectField fieldId) {

            Set<Id> assessmentItemIds = new Set<Id>();
            for (SObject r : records) {
                assessmentItemIds.add((Id)r.get(fieldId));
            }

            Map<Id, Assessment_Definition_Item__c> items = new Map<Id, Assessment_Definition_Item__c>(
                [SELECT Id, Assessment_Definition__c
                    FROM Assessment_Definition_Item__c
                    WHERE Id in :assessmentItemIds]
                );
            return items;

        }

    }

}