force-app/main/default/objects/Assessment_Definition__c/Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition</label>
    <nameField>
        <label>Assessment Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Settings__c/Assessment_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Assessment Settings</label>
</CustomObject>

force-app/main/default/objects/Assessment_Settings__c/fields/ESW_Channel_Menu_Name__c.field-meta.xml
<CustomField>
    <fullName>ESW_Channel_Menu_Name__c</fullName>
    <label>ESW Channel Menu Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Settings__c/fields/Live_Agent_URL__c.field-meta.xml
<CustomField>
    <fullName>Live_Agent_URL__c</fullName>
    <label>Live Agent URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAssessmentDefinitionPreviewExtension.cls
@isTest
private with sharing class TestAssessmentDefinitionPreviewExtension {

    @isTest
    static void testExtension() {

        Assessment_Settings__c settings = new Assessment_Settings__c();
        settings.Live_Agent_URL__c = 'live agent url';
        settings.ESW_Channel_Menu_Name__c = 'esw live agent dev name';
        insert settings;

        Assessment_Definition__c def = TestAssessmentUtil.createTestAssessmentDefinition();

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(def);
        AssessmentDefinitionPreviewExtension ext = new AssessmentDefinitionPreviewExtension(sc);

        System.assertEquals('live agent url', ext.laEndpoint);
        System.assertEquals('esw live agent dev name', ext.eswChannelMenuName);
        System.assertNotEquals(null, ext.orgId);
        System.assertNotEquals(null, ext.orgUrl);

        Test.stopTest();

    }

}