force-app/main/default/objects/Assessment_Definition__c/Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition</label>
    <nameField>
        <label>Assessment Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Settings__c/Assessment_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Assessment Settings</label>
</CustomObject>

force-app/main/default/objects/Assessment_Settings__c/fields/ESW_Channel_Menu_Name__c.field-meta.xml
<CustomField>
    <fullName>ESW_Channel_Menu_Name__c</fullName>
    <label>ESW Channel Menu Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Settings__c/fields/Live_Agent_URL__c.field-meta.xml
<CustomField>
    <fullName>Live_Agent_URL__c</fullName>
    <label>Live Agent URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssessmentDefinitionPreviewExtension.cls
public with sharing class AssessmentDefinitionPreviewExtension {

    private final Assessment_Definition__c def;
    public String orgId{get; private set;}
    public String orgUrl{get; private set;}
    public String laEndpoint{get; private set;}
    public String eswChannelMenuName{get; private set;}

    public AssessmentDefinitionPreviewExtension(ApexPages.StandardController con) {
        this.def = (Assessment_Definition__c)con.getRecord();
        initParams();
    }

    private void initParams() {
        Assessment_Settings__c settings = Assessment_Settings__c.getInstance();
        this.orgId = UserInfo.getOrganizationId().substring(0, 15);
        this.orgUrl = URL.getOrgDomainUrl().toExternalForm();
        this.laEndpoint = settings.Live_Agent_URL__c;
        this.eswChannelMenuName = settings.ESW_Channel_Menu_Name__c;
    }

}