force-app/main/default/objects/Assessment_Definition__c/Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition</label>
    <nameField>
        <label>Assessment Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Session__c/Assessment_Session__c.object-meta.xml
<CustomObject>
    <label>Assessment Session</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Assessment Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Sessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Session__c/fields/Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Definition</label>
    <referenceTo>Assessment_Definition__c</referenceTo>
    <relationshipLabel>Assessment Sessions</relationshipLabel>
    <relationshipName>Assessment_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Session__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAssessmentSessionBatchUpdateService.cls
@isTest
private with sharing class TestAssessmentSessionBatchUpdateService {

    public static String CRON_EXP = '0 0 0 15 3 ? 2024';

    @isTest
    static void testAssessmentSessionBatchUpdateService() {

        Assessment_Definition__c def = createTestAssessmentDefinitionWitSessions();
        
        Test.startTest();
            AssessmentSessionBatchUpdateService batchJob = new AssessmentSessionBatchUpdateService();
            Database.executeBatch(batchJob);
        Test.stopTest();

        assertProcessedSessions(def);

    }

    @isTest
    static void testAssessmentSessionBatchUpdateServiceWithValidTranscript() {
        String lct1Id = createLiveChatTranscript();
        Assessment_Definition__c def = createTestAssessmentDefinitionWitSessions();
        Assessment_Session__c sess6 = TestAssessmentUtil.createAssessmentSession(def.Id, 'Completed', lct1Id);

        Test.startTest();
            AssessmentSessionBatchUpdateService batchJob = new AssessmentSessionBatchUpdateService();
            Database.executeBatch(batchJob);
        Test.stopTest();

        assertProcessedSessions(def);
    }

    @isTest
    static void testAssessmentSessionBatchUpdateScheduledJob() {

        Assessment_Definition__c def = createTestAssessmentDefinitionWitSessions();

        Test.startTest();
            String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new AssessmentScheduledActions());
        Test.stopTest();

    }

    private static Assessment_Definition__c createTestAssessmentDefinitionWitSessions() {
        Assessment_Definition__c def = TestAssessmentUtil.createTestAssessmentDefinition();
        Assessment_Session__c sess1 = TestAssessmentUtil.createAssessmentSession(def.Id, 'In Progress');
        Assessment_Session__c sess2 = TestAssessmentUtil.createAssessmentSession(def.Id, 'Completed');
        Assessment_Session__c sess3 = TestAssessmentUtil.createAssessmentSession(def.Id, 'Completed');
        Assessment_Session__c sess4 = TestAssessmentUtil.createAssessmentSession(def.Id, 'Completed', 'some-chat-key');
        Assessment_Session__c sess5 = TestAssessmentUtil.createAssessmentSession(def.Id, 'Completed', '5708A000000JHFCQA4');
        return def;
    }

    private static void assertProcessedSessions(Assessment_Definition__c def) {
        List<Assessment_Session__c> sessions = TestAssessmentUtil.getAssessmentSessionsByDefinitionIds(new Set<Id>{def.Id});
        for (Assessment_Session__c s : sessions) {
            if (s.Status__c == 'Completed') {
                System.assertEquals(true, s.Processed__c);
            } else {
                System.assertEquals(false, s.Processed__c);
            }
        }
    }

    private static String createLiveChatTranscript() {
        LiveChatVisitor lcv = new LiveChatVisitor();
        try {
            insert lcv;
        } catch(Exception e){}

        LiveChatTranscript lct = new LiveChatTranscript();
        lct.LiveChatVisitorid = lcv.id;
        try{
            insert lct;
        } catch(Exception e){}
        return lct.Id;
    }

}