force-app/main/default/objects/Assessment_Definition__c/Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition</label>
    <nameField>
        <label>Assessment Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition__c/fields/Assessment_Definition_Id__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Definition_Id__c</fullName>
    <externalId>true</externalId>
    <label>Assessment Definition Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestAssessmentDefinitionImportExportCtrl.cls
@isTest
private with sharing class TestAssessmentDefinitionImportExportCtrl {

    @isTest
    static void testExport() {
        Assessment_Definition__c def = TestAssessmentUtil.createTestAssessmentDefinition();

        Test.startTest();
            String exportJson = AssessmentDefinitionImportExportService.exportDefinition(def.Assessment_Definition_Id__c);
            Map<String, Object> objMap = (Map<String, Object>)JSON.deserializeUntyped(exportJson);
            System.assertEquals((String)def.Id, (String)objMap.get('Id'));
        Test.stopTest();
    }

    @isTest
    static void testImport() {
        Assessment_Definition__c def = TestAssessmentUtil.createTestAssessmentDefinition();
        String exportJson = AssessmentDefinitionImportExportService.exportDefinition(def.Assessment_Definition_Id__c);
        Map<String, Object> objMap = (Map<String, Object>)JSON.deserializeUntyped(exportJson);
        System.assertEquals((String)def.Id, (String)objMap.get('Id'));
        objMap.put('Assessment_Definition_Id__c',  def.Assessment_Definition_Id__c+'Copy');
        objMap.put('Name', def.Name+'Copy');
        List<SelectOption> opts = AssessmentDefinitionImportExportService.getDefinitionOptions();
        System.assertEquals(1, opts.size());

        Test.startTest();
            AssessmentDefinitionImportExportService.importDefinition(JSON.serialize(objMap));
            opts = AssessmentDefinitionImportExportService.getDefinitionOptions();
            System.assertEquals(2, opts.size());
        Test.stopTest();
    }

}