force-app/main/default/objects/Assessment_Definition__c/Assessment_Definition__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition</label>
    <nameField>
        <label>Assessment Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition_Item__c/Assessment_Definition_Item__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition Item</label>
    <nameField>
        <label>Assessment Definition Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definition Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition_Item__c/fields/Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Definition__c</fullName>
    <label>Assessment Definition</label>
    <referenceTo>Assessment_Definition__c</referenceTo>
    <relationshipLabel>Assessment Definition Items</relationshipLabel>
    <relationshipName>Assessment_Definition_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Assessment_Definition_Item_Event__c/Assessment_Definition_Item_Event__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition Item Event</label>
    <nameField>
        <displayFormat>AIE-{00000}</displayFormat>
        <label>Assessment Definition Item Event Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Definition Item Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition_Item_Event__c/fields/Assessment_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Definition</label>
    <referenceTo>Assessment_Definition__c</referenceTo>
    <relationshipLabel>Assessment Definition Item Events</relationshipLabel>
    <relationshipName>Assessment_Definition_Item_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Definition_Item_Event__c/fields/Assessment_Definition_Item__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Definition_Item__c</fullName>
    <label>Assessment Definition Item</label>
    <referenceTo>Assessment_Definition_Item__c</referenceTo>
    <relationshipLabel>Assessment Definition Item Events</relationshipLabel>
    <relationshipName>Assessment_Definition_Item_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/AssessmentDefItemEventTriggerHelper.cls
public with sharing class AssessmentDefItemEventTriggerHelper {

    public static void processBeforeInsert(List<Assessment_Definition_Item_Event__c> newRecords) {
        setAssessmentDefinitionIds(newRecords);
    }

    public static void processBeforeUpdate(Map<Id, Assessment_Definition_Item_Event__c> oldRecordsMap, Map<Id, Assessment_Definition_Item_Event__c> newRecordsMap) {
        setAssessmentDefinitionIds(newRecordsMap.values());
    }

    private static void setAssessmentDefinitionIds(List<Assessment_Definition_Item_Event__c> records) {
        AssessmentTriggerHelperUtil.setDefinitionId(records,
            Schema.Assessment_Definition_Item_Event__c.Assessment_Definition__c,
            Schema.Assessment_Definition_Item_Event__c.Assessment_Definition_Item__c);
    }

}