force-app/main/default/objects/Assessment_Definition_Item__c/Assessment_Definition_Item__c.object-meta.xml
<CustomObject>
    <label>Assessment Definition Item</label>
    <nameField>
        <label>Assessment Definition Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Definition Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Definition_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Message</fullName>
            </value>
            <value>
                <fullName>Alert</fullName>
            </value>
            <value>
                <fullName>Decision</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessmentDefItemTriggerHelper.cls
public with sharing class AssessmentDefItemTriggerHelper {

    public static void processBeforeInsert(List<Assessment_Definition_Item__c> newRecords) {
        setRecordTypeIds(newRecords);
    }

    private static void setRecordTypeIds(List<Assessment_Definition_Item__c> newRecords) {
        AssessmentDefItemTriggerHelper.WithoutSharingOps wsops = new AssessmentDefItemTriggerHelper.WithoutSharingOps();
        Map<String, Id> typeToRTIdMap = wsops.getItemTypeToRecordTypeIdMap();
        for (Assessment_Definition_Item__c r : newRecords) {
            r.RecordTypeId = typeToRTIdMap.get(r.Type__c);
        }
    }

    private without sharing class WithoutSharingOps {
        public Map<String, Id> getItemTypeToRecordTypeIdMap() {
            Map<String, Id> result = new Map<String, Id>();
            for(RecordType rt : [select Id, DeveloperName From RecordType where sobjecttype = 'Assessment_Definition_Item__c']){
                result.put(rt.DeveloperName, rt.Id);
            }
            return result;
        }
    }

}